### ISSUE TITLE
bug: index file not found, but returns status code 200

### ISSUE THREAD

**Issue by emartinez-dev** [emartinez-dev/webserv#13]
When entering a directory URL, if the Location has an index but we can't find that file, we should either return a status code of 404 or generate an autoindex.

## How to reproduce
With the configuration below, entering `http://127.0.0.1:8080/`, but there is no `noexiste.html` file

```yaml
location: 
        route: /
        root: /
        index:  noexiste.html
        autoindex: on 
        allow_methods: GET POST DELETE 
        cgi_ext: .php
```
