### ISSUE TITLE
bug: file exists but the response does not find it

### ISSUE THREAD

**Issue by emartinez-dev** [emartinez-dev/webserv#15]
With this config and file structure, when I go to `http://127.0.0.1:8080/html/limones.html`, it returns error 404, but it should find the `limones.html` file:

```yaml
    location: 
        route: /
        root: /
        autoindex: on 
        allow_methods: GET POST DELETE 
        cgi_ext: .php
```

```
example
├── alberto
│   └── index.html
├── hola
│   └── fuaa.txt
├── html
│   ├── big.jpg
│   ├── index.html
│   └── limones.html
├── indexnuevo.html
└── php
    └── index.php
```

These are the logs that the server prints, it seems that real_root doesn't have the html folder, it just puts `//`:

![image](https://github.com/emartinez-dev/webserv/assets/73340871/f487f32e-2281-4e7c-8602-2a8aad5453cc)
